version: '3.8'

services:
  video_app:
    build: .
    container_name: video_analytics
    ports:
      - "8000:8000"
      - "8554:8554"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - DISPLAY=:0

